### PR TITLE
Fix P4Dummy Backend Failure with External Input Program

### LINKED ISSUE #1: `p4dummy` fails with an externally supplied input program.
As specified in the title, the `p4dummy` backend fails when its supplied with an external input program.
It works fine when used with `--use-fixed`.

This should be an easy fix. Let me know if i should file a PR.

### PR DESCRIPTION
**Pull request by snapdgn**
Fixes #1

Let me know if this is ok.

### CODE REVIEW

**Comment by fruffy** [comment]
How are you invoking the program? This should not be necessary.

**Comment by fruffy** [comment]
Also what is the failure you are seeing?

**Comment by snapdgn** [comment]
> How are you invoking the program? This should not be necessary.

I'm invoking it as `./build/p4dummy example.p4`, relative to the p4c dir. This doesn't generate any error, but exits by printing the usage. 
Apologies if i've missed something obvious here(?)

**Comment by fruffy** [comment]
Thanks for finding this issue:
This patch should fix things, please test it and see whether it fixes your issue: 
```
diff --git a/dummy.cpp b/dummy.cpp
index 722875a..4507902 100644
--- a/dummy.cpp
+++ b/dummy.cpp
@@ -132,18 +133,16 @@ V1Switch(p(), vrfy(), ingress(), egress(), update(), deparser()) main;)";
 int main(int argc, char *const argv[]) {
     AutoCompileContext autoP4DummyContext(new P4Dummy::P4DummyContext);
     auto &options = P4Dummy::P4DummyContext::get().options();
-    options.langVersion = CompilerOptions::FrontendVersion::P4_16;
 
     if (options.process(argc, argv) == nullptr) {
         return EXIT_FAILURE;
     }
 
-    const IR::P4Program *program = nullptr;
-    if (options.file == nullptr && !options.useFixed) {
-        options.usage();
-        return EXIT_FAILURE;
+    if (!options.useFixed) {
+        options.setInputFile();
     }
 
+    const IR::P4Program *program = nullptr;
     if (options.useFixed) {
         program = P4Dummy::parseDummyP4(options);
     } else {
```

**Comment by snapdgn** [comment]
> see whether it fixes your issue

Thanks, this works.

I've updated the PR with the new patch.

**Review by fruffy — APPROVED** [review]
Thanks!

**Pull request merged**
